# POST Destino
POST http://localhost:3000/destinos/ HTTP/1.1
content-type: application/json 

{
    "nome": "Fernando de Noronha",
    "estado": "Pernambuco",
    "cidade": "Fernando de Noronha",
    "status": 1 
}