# POST Cliente
POST http://localhost:3000/clientes HTTP/1.1
content-type: application/json 

{
    "nome": "Murilo",
    "data_nascimento": "08/04/1996",
    "cpf": "123456789123",
    "contato": "algumacoisa@gmail.com",
    "sexo": "m",
    "status": "1"
}